version: "3.8"

services:
  app:
    container_name: docker_react_c
    image: docker-react_i
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - app-volume:/app
    ports: 
      - 3001:3000


volumes:
  app-volume:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /mnt/nfs/homes/clmurphy/Projects/Ft_transendence/transendence